server:
  port: 8080
spring:
#测试环境
  profiles:
    active: dev
#数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/wx?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    data-password: 123456
#输出SQL日志
  jpa:
    show-sql: true
  main:
    banner-mode: CONSOLE
#mybatis的配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.mofeisike.springcurddemo.entity.Area
#等级降低，可以输出SQL日志
logging:
  level:
    com.mofeisike.springcurddemo.dao: debug